if(EXISTS "/home/klxia/psort/oblsort/tests/test_algo[1]_tests.cmake")
  include("/home/klxia/psort/oblsort/tests/test_algo[1]_tests.cmake")
else()
  add_test(test_algo_NOT_BUILT test_algo_NOT_BUILT)
endif()
